name: Test NAS Connection

on:
  workflow_dispatch:  # Hanya dijalankan secara manual

jobs:
  test-nas-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH client and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client sshpass netcat-openbsd
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
    
    - name: Test NAS Connectivity
      env:
        NAS_HOST: ${{ secrets.NAS_HOST }}
        NAS_PORT: ${{ secrets.NAS_PORT }}
      run: |
        echo "Testing basic connectivity to NAS..."
        ping -c 4 $NAS_HOST || echo "Ping failed with status $?"
        
        echo "Testing if SSH port is open..."
        nc -z -v $NAS_HOST $NAS_PORT -w 10 || echo "Port check failed with status $?"
    
    - name: Test SSH Connection
      env:
        SSHPASS: ${{ secrets.NAS_PASSWORD }}
        NAS_HOST: ${{ secrets.NAS_HOST }}
        NAS_PORT: ${{ secrets.NAS_PORT }}
        NAS_USERNAME: ${{ secrets.NAS_USERNAME }}
      run: |
        echo "Testing SSH connection with verbose output..."
        export SSHPASS="$SSHPASS"
        sshpass -e ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=30 -p $NAS_PORT $NAS_USERNAME@$NAS_HOST 'echo "Connection successful"; hostname; whoami' || echo "SSH connection failed with status $?" 